-- 2026-08-26 — 조사팀이 찾아온 기관 229곳을 명부에 넣는다
--
-- 이 파일은 `scripts/orgs-add.mjs`가 만들었다. 조사팀이 낸 목록을 그대로 옮긴 것이다.
-- 명부는 아무나 못 쓰게 잠겨 있어서(그게 맞다) 마이그레이션으로만 들어간다.
--
-- 되돌리는 법:
--   delete from public.orgs where id in ('jongno1318', 'dodoit', 'sdyc', 'light1318', 'ddm1318', 'jn1318', 'sb1318', 'sb1318-2', 'gb1318', 'db1318', 'nowonyouthcenter', 'woori1318', 'sdm7979', 'mapo1388', 'yangcheon1388', 'gs1318', 'guro1318', 'gc1388', 'young1318', 'djyc1388', 'go1318', 'seocho1318', 'gnyc', 'sp1318', 'wagle', 'junggu1388', 'flyseogu1388', 'bsdg1388', 'busanyouth', 'bsjin1388', '1388youth', 'namgu1388', 'bsbukgu', 'u-dream', 'saha1388', 'gjyouth1388', 'yeonje1388', 'meetyou', 'sasang1388', 'gijangcmc', 'ymca1388', 'dg1388', 'seoguc8310', 'dng1388', 'teen1388', 'ss1388', 'dalbi1388', 'ds1388', 'gunwi', 'junggu1388-2', 'junggu1388-3', 'dream1388', 'michu1388', 'ysyouth', 'nd1388', 'portal', 'gyeyang1388', 'sg1388', 'ghycw', 'dg1388-2', 'happy1388', '1388namgu', 'ok1388', 'gsg1388', 'sgy1388', 'counsel', 'micos1388', 'friend5279', 'bukgu1388', 'ulju1388', 'ulju1388-2', 'syf', 'snyouth', 'uiyouth', 'ayf', 'zzang1318', 'gmyouth', 'pt1318', 'tistory', 'aycc', 'gcyf', 'gc1318', 'guri1388', 'nyj', 'osan1318', 'shyc', 'shyc-2', 'gp1388', 'uyf', 'hanam', 'yiyf', 'pajuyouth', 'ic1318', 'an1318', 'fgy', 'mars1318', 'ggj1388', 'yangju', 'pocheon', 'youth', 'yc1388', 'gp1318', 'yp21', 'cool1388', 'wonju1388', 'gangneung1388', 'dhyc', 'tb1388', 'sokcho1388', 'scc1388', 'hcyc1388', 'hsg1388', 'kyw1318', 'pc1388', 'jsyouth', 'youth-2', 'cj1388', '1388cw', 'chungstar', 'jc1318', 'boeun1388', 'oc', 'yd1388', 'jp1388', 'jc1388', 'goesan1388', 'es1388', 'danyang', 'cheonan', 'gj1318', 'dongmuya', 'asanyouth', 'haemaum', 'nsyouth', 'call1388', 'dangjin', 'gs1388', '1388buyeo', 'sycw1388', 'cy1388', 'hssd1388', 'yesanyouth', 'happy1388-2', 'jjsangdam', 'gunsan0924', 'jeonbuk-counsel', 'jeongeup', 'nw1388', 'youth-3', 'wanju1388', 'ja1388', 'mujuyouth', 'jeonbuk-counsel-2', 'cheongmoon', 'sc1388', 'gochang', 'jeonbuk-counsel-3', 'youth-4', 'ys1388', 'sc1388dream', 'nj1388', 'gy1388', 'dyy1388', 'gsyouth', 'jeonnam-counsel', 'jeonnam-counsel-2', 'bs1388', 'hs1388', 'jh1388', 'gjyouth', 'hyouth1388', 'ya1388', 'muan', 'nownow1388', 'yg1388', 'js1388', 'wd1388', 'jeonnam-counsel-3', 'shinan1388', 'phyf', 'youth-5', 'gc', 'ad1318', 'youthcoc', 'yj1318', 'yc', 'sj7942', 'gbmg', 'gbgs', 'counsel-2', 'youth1388', 'yyg', 'gyeongbuk-counsel', 'gyeongbuk-counsel-2', 'art', 'sjc1388', 'chilgok', 'gyeongbuk-counsel-3', 'bhw1318', 'uljin', 'changwon', 'changwon-2', 'changwon-3', 'youth-6', 'tycoun', 'youthsacheon', 'gimhae', 'gimhae-2', 'miryang1388', 'counsel-3', 'yangsan', 'uiryeong', 'haman1388', 'cng', 'gsyon', 'namhae', 'hadong', 'sancheong', 'gyeongnam-counsel', 'geochang', 'hc', 'seogwipo', 'jeju-counsel', 'busanyouth-2', 'active', 'inyouthvol', 'youth-7', 'gbywa', 'gnysf');

insert into public.orgs
  (id, name, org_type, region, categories, site, notice_url, reachable, harvest_cycle, note)
values
  ('jongno1318', '종로구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.jongno1318.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('dodoit', '용산구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.dodoit.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('sdyc', '성동구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://sdyc.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('light1318', '광진구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.light1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('ddm1318', '동대문구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.ddm1318.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('jn1318', '중랑구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.jn1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('sb1318', '성북구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.sb1318.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 404'),
  ('sb1318-2', '성북구석관청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.sb1318.or.kr', null, 'unknown', 'monthly', '성북구청소년상담복지센터와 같은 사이트(분원) · 실장 확인 404'),
  ('gb1318', '강북구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.gb1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('db1318', '도봉구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.db1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('nowonyouthcenter', '노원구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.nowonyouthcenter.org', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('woori1318', '은평구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.woori1318.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('sdm7979', '서대문구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.sdm7979.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('mapo1388', '마포구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.mapo1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('yangcheon1388', '양천구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'http://yangcheon1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('gs1318', '강서구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.gs1318.or.kr', null, 'open', 'monthly', 'data.go.kr 원본(CSV 시군구명 오탈자 "강성구" 확인, 명칭은 강서구 맞음) · 실장 확인 200'),
  ('guro1318', '구로구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.guro1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('gc1388', '금천구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.gc1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('young1318', '영등포구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.young1318.com', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('djyc1388', '동작구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'http://djyc1388.or.kr', null, 'open', 'monthly', 'CSV 원문 http · 실장 확인 200'),
  ('go1318', '관악구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'http://go1318.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('seocho1318', '서초구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'http://seocho1318.com', null, 'open', 'monthly', 'CSV 원문 http · 실장 확인 200'),
  ('gnyc', '강남구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.gnyc.or.kr', null, 'blocked', 'monthly', '조사 WebFetch ETIMEOUT · 실장 확인 연결 안 됨'),
  ('sp1318', '송파구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'https://www.sp1318.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('wagle', '강동구청소년상담복지센터', '지역거점', '서울', array['counseling']::text[], 'http://www.wagle.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('junggu1388', '부산중구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'https://www.junggu1388.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 406'),
  ('flyseogu1388', '부산서구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'https://www.flyseogu1388.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 406'),
  ('bsdg1388', '부산동구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'http://bsdg1388.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('busanyouth', '영도구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'https://www.busanyouth.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('bsjin1388', '부산진구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'http://bsjin1388.or.kr', null, 'open', 'monthly', 'CSV 원문 http · 실장 확인 200'),
  ('1388youth', '동래구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'https://www.1388youth.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('namgu1388', '부산남구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'https://www.namgu1388.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('bsbukgu', '부산북구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'http://www.bsbukgu.go.kr/youth', null, 'blocked', 'monthly', '구청 홈페이지 하위경로 · 실장 확인 503'),
  ('u-dream', '해운대구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'https://www.u-dream.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('saha1388', '사하구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'https://www.saha1388.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('gjyouth1388', '금정구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'https://www.gjyouth1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('yeonje1388', '연제구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'https://www.yeonje1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('meetyou', '수영구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'https://www.meetyou.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('sasang1388', '사상구청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'http://sasang1388.kr', null, 'open', 'monthly', 'CSV 원문 http · 실장 확인 200'),
  ('gijangcmc', '기장군청소년상담복지센터', '지역거점', '부산', array['counseling']::text[], 'http://gijangcmc.or.kr/1388/main/main.asp', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('ymca1388', '대구중구청소년상담복지센터', '지역거점', '대구', array['counseling']::text[], 'http://www.ymca1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('dg1388', '대구동구청소년상담복지센터', '지역거점', '대구', array['counseling']::text[], 'http://www.dg1388.or.kr', null, 'open', 'monthly', 'CSV 원문 http · 실장 확인 200'),
  ('seoguc8310', '대구서구청소년상담복지센터', '지역거점', '대구', array['counseling']::text[], 'https://www.seoguc8310.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('dng1388', '대구남구청소년상담복지센터', '지역거점', '대구', array['counseling']::text[], 'https://www.dng1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('teen1388', '대구북구청소년상담복지센터', '지역거점', '대구', array['counseling']::text[], 'https://www.teen1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('ss1388', '수성구청소년상담복지센터', '지역거점', '대구', array['counseling']::text[], 'http://ss1388.suseong.kr', null, 'blocked', 'monthly', '구청 하위 도메인 · 실장 확인 503'),
  ('dalbi1388', '달서구청소년상담복지센터', '지역거점', '대구', array['counseling']::text[], 'https://www.dalbi1388.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('ds1388', '대구달성군청소년상담복지센터', '지역거점', '대구', array['counseling']::text[], 'http://www.ds1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('gunwi', '군위군청소년상담복지센터', '지역거점', '대구', array['counseling']::text[], 'http://www.gunwi.go.kr', null, 'open', 'monthly', '군청 홈페이지, 2023년 대구 편입지역 · 실장 확인 200'),
  ('junggu1388-2', '인천중구청소년상담복지센터', '지역거점', '인천', array['counseling']::text[], 'https://www.junggu1388.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('junggu1388-3', '인천중구동인천청소년상담복지센터', '지역거점', '인천', array['counseling']::text[], 'https://www.junggu1388.kr', null, 'open', 'monthly', '인천중구청소년상담복지센터와 같은 사이트(분원) · 실장 확인 200'),
  ('dream1388', '인천동구청소년상담복지센터', '지역거점', '인천', array['counseling']::text[], 'https://www.dream1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('michu1388', '인천미추홀구청소년상담복지센터', '지역거점', '인천', array['counseling']::text[], 'https://www.michu1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('ysyouth', '연수구청소년상담복지센터', '지역거점', '인천', array['counseling']::text[], 'https://www.ysyouth.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('nd1388', '남동구청소년상담복지센터', '지역거점', '인천', array['counseling']::text[], 'http://nd1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('portal', '부평구청소년상담복지센터', '지역거점', '인천', array['counseling']::text[], 'http://portal.icbp.go.kr/1388', null, 'open', 'monthly', '구청 포털 하위경로 · 실장 확인 200'),
  ('gyeyang1388', '계양구청소년상담복지센터', '지역거점', '인천', array['counseling']::text[], 'https://www.gyeyang1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('sg1388', '인천서구청소년상담복지센터', '지역거점', '인천', array['counseling']::text[], 'https://www.sg1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('ghycw', '강화군청소년상담복지센터', '지역거점', '인천', array['counseling']::text[], 'http://ghycw.ganghwa.go.kr', null, 'open', 'monthly', '군청 하위 도메인 · 실장 확인 200'),
  ('dg1388-2', '광주동구청소년상담복지센터', '지역거점', '광주', array['counseling']::text[], 'https://www.dg1388.com', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('happy1388', '광주서구청소년상담복지센터', '지역거점', '광주', array['counseling']::text[], 'https://www.happy1388.com', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('1388namgu', '광주남구청소년상담복지센터', '지역거점', '광주', array['counseling']::text[], 'https://www.1388namgu.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('ok1388', '광주북구청소년상담복지센터', '지역거점', '광주', array['counseling']::text[], 'https://www.ok1388.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('gsg1388', '광산구청소년상담복지센터', '지역거점', '광주', array['counseling']::text[], 'https://www.gsg1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('sgy1388', '대전서구청소년상담복지센터', '지역거점', '대전', array['counseling']::text[], 'http://www.sgy1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('counsel', '유성구청소년상담복지센터', '지역거점', '대전', array['counseling']::text[], 'http://counsel.happyyc1318.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 연결 안 됨'),
  ('micos1388', '울산남구청소년상담복지센터', '지역거점', '울산', array['counseling']::text[], 'http://www.micos1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 연결 안 됨'),
  ('friend5279', '울산동구청소년상담복지센터', '지역거점', '울산', array['counseling']::text[], 'https://www.friend5279.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 503'),
  ('bukgu1388', '울산북구청소년상담복지센터', '지역거점', '울산', array['counseling']::text[], 'https://www.bukgu1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('ulju1388', '울주군청소년상담복지센터', '지역거점', '울산', array['counseling']::text[], 'https://www.ulju1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('ulju1388-2', '울주군중부청소년상담복지센터', '지역거점', '울산', array['counseling']::text[], 'https://www.ulju1388.or.kr', null, 'blocked', 'monthly', '울주군청소년상담복지센터와 같은 사이트(분원) · 실장 확인 연결 안 됨'),
  ('syf', '수원시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'http://www.syf.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('snyouth', '성남시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'http://www.snyouth.or.kr', null, 'blocked', 'monthly', '성남시청소년청년재단 산하 1388 · 실장 확인 503'),
  ('uiyouth', '의정부시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.uiyouth.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('ayf', '안양시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.ayf.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('zzang1318', '부천시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.zzang1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('gmyouth', '광명시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.gmyouth.org', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('pt1318', '평택시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.pt1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('tistory', '동두천시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'http://1388.tistory.com', null, 'open', 'monthly', '티스토리 블로그, 공식 도메인 아님 · 실장 확인 200'),
  ('aycc', '안산시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.aycc.org', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('gcyf', '고양시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.gcyf.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('gc1318', '과천시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.gc1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('guri1388', '구리시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'http://guri1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('nyj', '남양주시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.nyj.go.kr', null, 'open', 'monthly', '시청 홈페이지, 전용 도메인 아님 · 실장 확인 200'),
  ('osan1318', '오산시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.osan1318.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('shyc', '시흥시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.shyc.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('shyc-2', '시흥시정왕청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.shyc.or.kr', null, 'blocked', 'monthly', '시흥시청소년상담복지센터와 같은 사이트(분원) · 실장 확인 연결 안 됨'),
  ('gp1388', '군포시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.gp1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('uyf', '의왕시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.uyf.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('hanam', '하남시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.hanam.go.kr', null, 'open', 'monthly', '시청 홈페이지, 전용 도메인 아님 · 실장 확인 200'),
  ('yiyf', '용인시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.yiyf.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('pajuyouth', '파주시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.pajuyouth.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('ic1318', '이천시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.ic1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('an1318', '안성시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.an1318.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('fgy', '김포시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.fgy.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('mars1318', '화성시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.mars1318.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('ggj1388', '광주시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.ggj1388.or.kr', 'https://ggj1388.or.kr/bbs/board.php?bo_table=notice01', 'open', 'monthly', '경기도 광주시(광주광역시 아님) · 실장 확인 200'),
  ('yangju', '양주시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.yangju.go.kr', null, 'open', 'monthly', '시청 홈페이지, 전용 도메인 아님 · 실장 확인 200'),
  ('pocheon', '포천시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'http://www.pocheon.go.kr', null, 'open', 'monthly', '시청 홈페이지, 전용 도메인 아님 · 실장 확인 200'),
  ('youth', '여주시청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'http://youth.yeoju.go.kr', null, 'blocked', 'monthly', '시청 하위 도메인 · 실장 확인 연결 안 됨'),
  ('yc1388', '연천군청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.yc1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('gp1318', '가평군청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.gp1318.com', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('yp21', '양평군청소년상담복지센터', '지역거점', '경기', array['counseling']::text[], 'https://www.yp21.go.kr', null, 'blocked', 'monthly', '군청 홈페이지, 전용 도메인 아님 · 실장 확인 연결 안 됨'),
  ('cool1388', '춘천시청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'http://www.cool1388.com', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 연결 안 됨'),
  ('wonju1388', '원주시청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'https://www.wonju1388.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('gangneung1388', '강릉시청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'https://www.gn1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('dhyc', '동해시청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'http://www.dhyc.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 연결 안 됨'),
  ('tb1388', '태백시청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'https://www.tb1388.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('sokcho1388', '속초시청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'https://www.sokcho1388.org', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('scc1388', '삼척시청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'http://scc1388.co.kr', null, 'open', 'monthly', 'CSV 원문 http · 실장 확인 200'),
  ('hcyc1388', '홍천군청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'https://www.hcyc1388.org', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('hsg1388', '횡성군청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'http://hsg1388.modoo.at', null, 'open', 'monthly', 'modoo 홈페이지, 전용 도메인 아님 · 실장 확인 200'),
  ('kyw1318', '영월군청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'https://www.kyw1318.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('pc1388', '평창군청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'http://www.pc1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('jsyouth', '정선군청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'http://www.jsyouth.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('youth-2', '철원군청소년상담복지센터', '지역거점', '강원', array['counseling']::text[], 'http://youth.cwg.go.kr', null, 'blocked', 'monthly', '군청 하위 도메인 · 실장 확인 연결 안 됨'),
  ('cj1388', '청주시청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'https://www.cj1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('1388cw', '서청주청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'http://www.1388cw.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('chungstar', '충주시청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'https://www.chungstar.org', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('jc1318', '제천시청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'https://www.jc1318.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('boeun1388', '보은군청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'https://www.boeun1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('oc', '옥천군청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'https://www.oc.go.kr/youth', null, 'open', 'monthly', '군청 하위경로 · 실장 확인 200'),
  ('yd1388', '영동군청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'https://www.yd1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('jp1388', '증평군청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'https://www.jp1388.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('jc1388', '진천군청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'http://jc1388.co.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('goesan1388', '괴산군청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'http://www.goesan1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('es1388', '음성군청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'https://www.es1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('danyang', '단양군청소년상담복지센터', '지역거점', '충북', array['counseling']::text[], 'https://www.danyang.go.kr/dy1388', null, 'open', 'monthly', '군청 하위경로 · 실장 확인 200'),
  ('cheonan', '천안시청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.cheonan.go.kr/teen.do', null, 'blocked', 'monthly', '시청 하위경로 · 실장 확인 연결 안 됨'),
  ('gj1318', '공주시청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'http://www.gj1318.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('dongmuya', '보령시청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.dongmuya.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('asanyouth', '아산시청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'http://www.asanyouth.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('haemaum', '서산시청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.haemaum.com', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('nsyouth', '논산시청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.nsyouth.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('call1388', '계룡시청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'http://www.call1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 연결 안 됨'),
  ('dangjin', '당진시청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'http://www.dangjin.go.kr/dj1388.do', null, 'blocked', 'monthly', '시청 하위경로 · 실장 확인 503'),
  ('gs1388', '금산군청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.gs1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('1388buyeo', '부여군청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.1388buyeo.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('sycw1388', '서천군청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.sycw1388.co.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('cy1388', '청양군청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.cy1388.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('hssd1388', '홍성군청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.hssd1388.com', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('yesanyouth', '예산군청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.yesanyouth.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('happy1388-2', '태안군청소년상담복지센터', '지역거점', '충남', array['counseling']::text[], 'https://www.happy1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('jjsangdam', '전주시청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'http://www.jjsangdam.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 연결 안 됨'),
  ('gunsan0924', '군산시청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'https://www.gunsan0924.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 503'),
  ('jeonbuk-counsel', '익산시청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], null, null, 'unknown', 'monthly', 'CSV 원문 주소 표기 깨짐, 확인 못 함'),
  ('jeongeup', '정읍시청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'https://jeongeup.go.kr', null, 'blocked', 'monthly', '시청 홈페이지, 전용 도메인 아님 · 실장 확인 503'),
  ('nw1388', '남원시청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'https://www.nw1388.com', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('youth-3', '김제시청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'http://youth.gimje.go.kr', null, 'blocked', 'monthly', '시청 하위 도메인 · 실장 확인 503'),
  ('wanju1388', '완주군청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'http://www.wanju1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('ja1388', '진안군청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'https://www.ja1388.com', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('mujuyouth', '무주군청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'https://www.mujuyouth.net', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('jeonbuk-counsel-2', '장수군청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], null, null, 'unknown', 'monthly', '페이스북 페이지만 있음(공식 홈페이지 없음)'),
  ('cheongmoon', '임실군청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'https://cheongmoon.tistory.com', null, 'open', 'monthly', '티스토리 블로그, 공식 도메인 아님 · 실장 확인 200'),
  ('sc1388', '순창군청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'https://www.sc1388.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 406'),
  ('gochang', '고창군청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], 'https://www.gochang.go.kr', null, 'open', 'monthly', '군청 하위경로 · 실장 확인 200'),
  ('jeonbuk-counsel-3', '부안군청소년상담복지센터', '지역거점', '전북', array['counseling']::text[], null, null, 'unknown', 'monthly', '페이스북 페이지만 있음(공식 홈페이지 없음)'),
  ('youth-4', '목포시청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'http://youth.mokpo.go.kr', null, 'blocked', 'monthly', '시청 하위 도메인 · 실장 확인 503'),
  ('ys1388', '여수시청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.ys1388.or.kr', null, 'open', 'monthly', '조사 WebFetch 503 · 실장 확인 200'),
  ('sc1388dream', '순천시청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.sc1388dream.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('nj1388', '나주시청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.nj1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('gy1388', '광양시청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.gy1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('dyy1388', '담양군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.dyy1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('gsyouth', '곡성군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'http://1388.gsyouth.kr', null, 'open', 'monthly', 'CSV 원문 http · 실장 확인 200'),
  ('jeonnam-counsel', '구례군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], null, null, 'unknown', 'monthly', '인스타그램만 있음(공식 홈페이지 없음)'),
  ('jeonnam-counsel-2', '고흥군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], null, null, 'unknown', 'monthly', '다음카페만 있음(공식 홈페이지 없음)'),
  ('bs1388', '보성군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'http://bs1388.co.kr', null, 'unknown', 'monthly', 'CSV 원문 http · 실장 확인 403'),
  ('hs1388', '화순군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'http://www.hs1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('jh1388', '장흥군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'http://www.jh1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('gjyouth', '강진군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.gjyouth.co.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('hyouth1388', '해남군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'http://www.hyouth1388.co.kr', null, 'open', 'monthly', 'CSV 원문 http · 실장 확인 200'),
  ('ya1388', '영암군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.ya1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('muan', '무안군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.muan.go.kr', null, 'open', 'monthly', '군청 하위경로 · 실장 확인 200'),
  ('nownow1388', '함평군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.nownow1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('yg1388', '영광군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.yg1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('js1388', '장성군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'https://www.js1388.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('wd1388', '완도군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'http://wd1388.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('jeonnam-counsel-3', '진도군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], null, null, 'unknown', 'monthly', '네이버카페만 있음(공식 홈페이지 없음)'),
  ('shinan1388', '신안군청소년상담복지센터', '지역거점', '전남', array['counseling']::text[], 'http://www.shinan1388.com', null, 'open', 'monthly', 'CSV 원문 http · 실장 확인 200'),
  ('phyf', '포항시청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'http://www.phyf.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('youth-5', '경주시청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'http://youth.gyeongju.go.kr', null, 'blocked', 'monthly', '시청 하위 도메인 · 실장 확인 503'),
  ('gc', '김천시청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'https://www.gc.go.kr', null, 'unknown', 'monthly', '시청 홈페이지, 전용 도메인 아님 · 실장 확인 404'),
  ('ad1318', '안동시청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'https://www.ad1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('youthcoc', '구미시청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'https://www.youthcoc.org', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('yj1318', '영주시청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'http://yj1318.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('yc', '영천시청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'http://1388.yc.go.kr', null, 'blocked', 'monthly', '시청 하위 도메인 · 실장 확인 연결 안 됨'),
  ('sj7942', '상주시청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'https://www.sj7942.org', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('gbmg', '문경시청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'https://www.gbmg.go.kr', null, 'open', 'monthly', '시청 하위경로 · 실장 확인 200'),
  ('gbgs', '경산시청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'http://gbgs.go.kr/special/young/index.do', null, 'open', 'monthly', '시청 하위경로 · 실장 확인 200'),
  ('counsel-2', '의성군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'http://counsel.usyouth.go.kr', null, 'blocked', 'monthly', '군청 하위 도메인 · 실장 확인 연결 안 됨'),
  ('youth1388', '청송군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'https://www.youth1388.or.kr', null, 'open', 'monthly', 'data.go.kr 원본 · 실장 확인 200'),
  ('yyg', '영양군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'https://yyg.go.kr/youth/yyg1388', null, 'unknown', 'monthly', '군청 하위경로 · 실장 확인 404'),
  ('gyeongbuk-counsel', '영덕군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], null, null, 'unknown', 'monthly', '페이스북 페이지만 있음(공식 홈페이지 없음)'),
  ('gyeongbuk-counsel-2', '청도군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], null, null, 'unknown', 'monthly', '다음카페만 있음(공식 홈페이지 없음)'),
  ('art', '고령군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'http://art.goryeong.go.kr', null, 'blocked', 'monthly', '군청 문화사이트 하위경로 · 실장 확인 연결 안 됨'),
  ('sjc1388', '성주군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'https://sjc1388.co.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('chilgok', '칠곡군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'https://www.chilgok.go.kr', null, 'open', 'monthly', '군청 하위경로 · 실장 확인 200'),
  ('gyeongbuk-counsel-3', '예천군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], null, null, 'unknown', 'monthly', '다음카페만 있음(공식 홈페이지 없음)'),
  ('bhw1318', '봉화군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'https://www.bhw1318.or.kr', null, 'blocked', 'monthly', 'data.go.kr 원본 · 실장 확인 연결 안 됨'),
  ('uljin', '울진군청소년상담복지센터', '지역거점', '경북', array['counseling']::text[], 'http://www.uljin.go.kr', null, 'blocked', 'monthly', '군청 홈페이지, 전용 도메인 아님 · 실장 확인 503'),
  ('changwon', '창원시창원청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'https://www.changwon.go.kr', null, 'open', 'monthly', '시청 하위경로 · 실장 확인 200'),
  ('changwon-2', '창원시마산청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'https://www.changwon.go.kr', null, 'open', 'monthly', '창원시창원청소년상담복지센터와 같은 시청 사이트(분원) · 실장 확인 200'),
  ('changwon-3', '창원시진해청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'https://www.changwon.go.kr', null, 'open', 'monthly', '상동(분원) · 실장 확인 200'),
  ('youth-6', '진주시청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'http://youth.jinju.go.kr', null, 'blocked', 'monthly', '시청 하위 도메인 · 실장 확인 503'),
  ('tycoun', '통영시청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'https://www.tycoun.or.kr', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('youthsacheon', '사천시청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'https://www.youthsacheon.com', null, 'unknown', 'monthly', 'data.go.kr 원본 · 실장 확인 403'),
  ('gimhae', '김해시청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'https://www.gimhae.go.kr', null, 'open', 'monthly', '시청 하위경로 · 실장 확인 200'),
  ('gimhae-2', '김해시서부청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'https://www.gimhae.go.kr', null, 'open', 'monthly', '김해시청소년상담복지센터와 같은 시청 사이트(분원) · 실장 확인 200'),
  ('miryang1388', '밀양시청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'http://www.miryang1388.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('counsel-3', '거제시청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'http://counsel.geoje.go.kr', null, 'blocked', 'monthly', '시청 하위 도메인 · 실장 확인 연결 안 됨'),
  ('yangsan', '양산시청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'http://www.yangsan.go.kr/teen/main.do', null, 'open', 'monthly', '시청 하위경로 · 실장 확인 200'),
  ('uiryeong', '의령군청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'http://www.uiryeong.go.kr', null, 'blocked', 'monthly', '군청 하위경로 · 실장 확인 503'),
  ('haman1388', '함안군청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'http://www.haman1388.or.kr', null, 'open', 'monthly', 'CSV 원문 http · 실장 확인 200'),
  ('cng', '창녕군청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'http://www.cng.go.kr', null, 'blocked', 'monthly', '군청 하위경로 · 실장 확인 연결 안 됨'),
  ('gsyon', '고성군청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'http://www.gsyon.or.kr', null, 'blocked', 'monthly', 'CSV 원문 http · 실장 확인 503'),
  ('namhae', '남해군청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'https://www.namhae.go.kr', null, 'blocked', 'monthly', '군청 홈페이지, 전용 도메인 아님 · 실장 확인 연결 안 됨'),
  ('hadong', '하동군청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'https://www.hadong.go.kr', null, 'open', 'monthly', '군청 하위경로 · 실장 확인 200'),
  ('sancheong', '산청군청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'https://www.sancheong.go.kr', null, 'blocked', 'monthly', '군청 홈페이지, 전용 도메인 아님 · 실장 확인 연결 안 됨'),
  ('gyeongnam-counsel', '함양군청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], null, null, 'unknown', 'monthly', 'CSV 원문 주소가 함안군과 동일 — 원본 오류로 보임, 확인 못 함'),
  ('geochang', '거창군청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'http://www.geochang.go.kr', null, 'open', 'monthly', '군청 하위경로 · 실장 확인 200'),
  ('hc', '합천군청소년상담복지센터', '지역거점', '경남', array['counseling']::text[], 'http://www.hc.go.kr', null, 'open', 'monthly', '군청 하위경로 · 실장 확인 200'),
  ('seogwipo', '서귀포시청소년상담복지센터', '지역거점', '제주', array['counseling']::text[], 'http://www.seogwipo.go.kr', null, 'blocked', 'monthly', '시청 하위경로 · 실장 확인 503'),
  ('jeju-counsel', '제주시청소년상담복지센터', '지역거점', '제주', array['counseling']::text[], null, null, 'unknown', 'monthly', 'CSV 원문 주소가 한글 도메인이라 확인 못 함'),
  ('busanyouth-2', '부산광역시청소년활동진흥센터', '공공', '부산', array['contest']::text[], 'https://busanyouth.net', null, 'open', 'monthly', 'WebSearch로 도메인 확인 · 실장 확인 200'),
  ('active', '대구광역시청소년활동진흥센터', '공공', '대구', array['contest']::text[], 'https://active.daeguyouth.net', 'https://active.daeguyouth.net/Board/view.asp?board=ActiveNotice', 'open', 'monthly', 'WebSearch로 확인, 공지 게시판 확보 · 실장 확인 200'),
  ('inyouthvol', '인천광역시청소년활동진흥센터', '공공', '인천', array['contest']::text[], 'https://www.inyouthvol.net', null, 'open', 'monthly', 'WebSearch로 확인 · 실장 확인 200'),
  ('youth-7', '전라남도청소년미래재단 청소년활동진흥센터', '공공', '전남', array['contest']::text[], 'https://youth.jnyouth.or.kr', null, 'open', 'monthly', 'WebSearch로 확인 · 실장 확인 200'),
  ('gbywa', '경상북도청소년활동진흥센터', '공공', '경북', array['contest']::text[], 'https://gbywa.or.kr', null, 'open', 'monthly', 'WebSearch로 확인 · 실장 확인 200'),
  ('gnysf', '경상남도청소년지원재단', '공공', '경남', array['contest']::text[], 'https://gnysf.co.kr', null, 'open', 'monthly', '상담·활동·긴급지원 통합 운영 · 실장 확인 200')
on conflict (id) do update set
  name         = excluded.name,
  org_type     = excluded.org_type,
  region       = excluded.region,
  categories   = coalesce(excluded.categories, public.orgs.categories),
  site         = coalesce(excluded.site, public.orgs.site),
  notice_url   = coalesce(excluded.notice_url, public.orgs.notice_url),
  note         = coalesce(excluded.note, public.orgs.note);
